const reviews = [
    {
      avatarSrc: '...',
      author: 'Brad Adams',
      id: 1,
      date: '12 SEP 2012',
      content: 'aaaaaaaaa Nội dung thảo luận trên diễn đàn',
      likes: 12,
      comments: 8,
      shares: 4,
    },

    {
        avatarSrc: '...',
        author: 'Brad Adams',
        id:1,
        date: '12 SEP 2012',
        content: 'Nội dung thảo luận trên diễn đàn Nội dung thảo luận trên diễn đàn Nội dung thảo luận trên diễn đàn Nội dung thảo luận trên diễn đàn Nội dung thảo luận trên diễn đàn Nội dung thảo luận trên diễn đàn',
        likes: 19,
        comments: 8,
        shares: 7,
      },
      {
        avatarSrc: '...',
        author: 'Brad Adams',
        id:1,
        date: '12 SEP 2012',
        content: 'Nội dung thảo luận trên diễn đàn',
        likes: 12,
        comments: 8,
        shares: 4,
      },
      {
        avatarSrc: '...',
        author: 'Brad Adams',
        id:1,
        date: '12 SEP 2012',
        content: 'Nội dung thảo luận trên diễn đàn',
        likes: 12,
        comments: 8,
        shares: 4,
      },
      {
        avatarSrc: '...',
        author: 'Brad Adams',
        id:1,
        date: '12 SEP 2012',
        content: 'Nội dung thảo luận trên diễn đàn',
        likes: 12,
        comments: 8,
        shares: 4,
      },
      {
        avatarSrc: '...',
        author: 'Brad Adams',
        id:1,
        date: '12 SEP 2012',
        content: 'Nội dung thảo luận trên diễn đàn',
        likes: 12,
        comments: 8,
        shares: 4,
      },
      {
        avatarSrc: '...',
        author: 'Brad Adams',
        id:1,
        date: '12 SEP 2012',
        content: 'Nội dung thảo luận trên diễn đàn',
        likes: 12,
        comments: 8,
        shares: 4,
      },

  ];
export default reviews;